apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: creative-journey-com-tls
spec:
  secretName: creative-journey-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: creativejourney.com
  dnsNames:
    - creativejourney.com
    - www.creativejourney.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - creativejourney.com
          - www.creativejourney.com

